name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache CMAKE
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake
        
    - name: Cache GLUT
      id: cache-glut
      uses: actions/cache@v3
      with:
        path: freeglut-MSVC-3.0.0-2.mp.zip
        key: ${{ runner.os }}-glut
        
    - name: Download GLUT
      if: steps.cache-glut.outputs.cache-hit != 'true'
      run: |
        curl https://www.transmissionzero.co.uk/files/software/development/GLUT/freeglut-MSVC.zip \
          -o freeglut-MSVC.zip
        
    - name: Install GLUT
      run: |
        7za x freeglut-MSVC.zip
        mv freeglut/include/GL/* C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/include
        mv freeglut/lib/x64/* C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/lib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target main

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "main"
        files: |
          build/main.exe
          freeglut/bin/x64/*
          freeglut/bin/*
      
